const sectors=["Tous","Technologie","Finance","Pharmaceutique","Immobilier","Spatial","Énergie","Politique","Économie","Général"];
let state={articles:[],selected:"Tous",query:"",watch:JSON.parse(localStorage.getItem("watch")||"[]")};
const $=id=>document.getElementById(id);
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function attr(s){return esc(s).replace(/javascript:/gi,"")}
async function loadNews(){try{const r=await fetch("data/news.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error();const d=await r.json();state.articles=d.articles||[];$('updated').textContent=d.updatedAt?"Mis à jour "+new Date(d.updatedAt).toLocaleString("fr-CA"):"";chips();render()}catch(e){$('feed').innerHTML='<div class="empty">Impossible de charger les nouvelles.</div>'}}
function chips(){$('chips').innerHTML=sectors.map(s=>`<button class="${s===state.selected?"active":""}" onclick="state.selected='${esc(s)}';chips();render()">${s}</button>`).join("")}
function analysisPill(a){if(!a)return "";const cls=a.direction==="positif"?"positive":a.direction==="négatif"?"negative":"neutral";const sign=a.direction==="positif"?"↗":a.direction==="négatif"?"↘":"→";return `<span class="pill ${cls}">${sign} ${a.score}</span>`}
function render(){const arr=state.articles.filter(n=>(state.selected==="Tous"||n.sector===state.selected)&&(!state.query||(`${n.title} ${n.summary} ${n.source} ${(n.entities||[]).join(" ")} ${n.sector}`).toLowerCase().includes(state.query.toLowerCase())));$('count').textContent=arr.length+" nouvelles";$('feed').innerHTML=arr.length?arr.map(n=>`<article class="card" onclick="openArticle('${attr(n.id)}')" role="button"><div class="cardlink"><div class="meta">${esc(n.sector)} · ${esc(n.source)} · ${n.sourceType==="officiel"?"SOURCE OFFICIELLE":n.sourceType==="agrégé"?"SOURCE AGRÉGÉE":"ÉCONOPULSE"}</div><h3>${esc(n.title)}</h3><div class="summary">${esc(n.summary||"")}</div><div class="impact"><span class="pill ${n.impact==="important"?"important":"neutral"}">${n.impact==="important"?"⚡ Important":"• À surveiller"}</span>${analysisPill(n.analysis)}${(n.entities||[]).slice(0,4).map(e=>`<span class="pill">${esc(e)}</span>`).join("")}</div>${n.analysis?`<div class="analysisline">Impact ${esc(n.analysis.magnitude)} · confiance ${esc(n.analysis.confidence)}%</div>`:""}</div></article>`).join(""): '<div class="empty">Aucune nouvelle trouvée.</div>'}
function openArticle(id){const n=state.articles.find(x=>x.id===id);if(!n)return;const a=n.analysis||{};$('modalBody').innerHTML=`<div class="meta">${esc(n.sector)} · ${esc(n.source)}</div><h2>${esc(n.title)}</h2><p>${esc(n.summary||"")}</p><h4>Analyse ÉconoPulse</h4><div class="analysisbox"><div class="score">${a.score??"—"} <small>/100</small></div><div><b>Impact ${esc(a.direction||"—")}</b><br>Intensité ${esc(a.magnitude||"—")} · confiance ${esc(a.confidence||"—")}%</div></div><p>${esc(a.explanation||"Analyse en attente.")}</p>${a.potentialWinners?.length?`<h4>Potentiellement favorisées</h4><div class="impact">${a.potentialWinners.map(e=>`<span class="pill positive">${esc(e)}</span>`).join("")}</div>`:""}${a.potentialRisks?.length?`<h4>Potentiellement exposées</h4><div class="impact">${a.potentialRisks.map(e=>`<span class="pill negative">${esc(e)}</span>`).join("")}</div>`:""}<p class="disclaimer">${esc(a.disclaimer||"Analyse indicative.")}</p><a class="brief" href="${attr(n.url)}" target="_blank" rel="noopener">Lire la source ↗</a>`;$('modal').classList.remove('hidden');$('modal').setAttribute('aria-hidden','false')}
function closeModal(){$('modal').classList.add('hidden');$('modal').setAttribute('aria-hidden','true')}
function showWatch(){const arr=state.articles.filter(n=>(n.entities||[]).some(e=>state.watch.includes(e)));$('count').textContent=arr.length+" nouvelles";$('feed').innerHTML=arr.length?arr.map(n=>`<article class="card" onclick="openArticle('${attr(n.id)}')"><div class="meta">${esc(n.source)} · ${esc(n.sector)}</div><h3>${esc(n.title)}</h3><div class="summary">${esc(n.summary||"")}</div><div class="impact">${(n.entities||[]).filter(e=>state.watch.includes(e)).map(e=>`<span class="pill">${esc(e)}</span>`).join("")}</div></article>`).join(""):'<div class="empty">Aucune entreprise suivie pour le moment.</div>'}
function showSources(){$('count').textContent="";$('feed').innerHTML='<div class="card"><h3>Sources V2.2</h3><p class="summary">Sources officielles : Banque du Canada, Federal Reserve, BCE, Statistique Canada et Maison-Blanche.</p><p class="summary">Couverture élargie : GDELT.</p><p class="summary">Les sources officielles sont distinguées des sources agrégées.</p></div>'}
$('search').addEventListener('input',e=>{state.query=e.target.value;render()});$('watchBtn').addEventListener('click',()=>{state.selected="Tous";state.query="";$('search').value="";showWatch()});$('closeModal').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=b.dataset.page;if(p==='home'){$('pageTitle').innerHTML='Ce qui bouge<br><span>aujourd’hui.</span>';chips();render()}else if(p==='sectors'){$('pageTitle').innerHTML='Explorez les<br><span>secteurs.</span>';chips();render()}else if(p==='watch'){$('pageTitle').innerHTML='Vos<br><span>suivis.</span>';showWatch()}else{$('pageTitle').innerHTML='Les<br><span>sources.</span>';showSources()}}));loadNews();
